# Generated by Django 3.2.4 on 2021-06-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemdashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.AddField(
            model_name='item',
            name='itemid',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
