# Generated by Django 3.2.4 on 2021-06-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemdashboard', '0002_auto_20210626_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemid',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
