# Generated by Django 3.2.4 on 2021-06-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemdashboard', '0003_alter_item_itemid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
